name: smart_garden_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  provider: ^6.0.0
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^24.2.6
  fl_chart: ^0.67.0
  linear_timer: ^2.0.0
  wifi_iot: ^0.3.19
  network_info_plus: ^5.0.2
  url_launcher: ^6.2.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
