// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cPHW1Vie1sfCNnLh09TpMUO-65_zijo',
    appId: '1:1000802414043:web:05a23976ad9e5ecb424bfe',
    messagingSenderId: '1000802414043',
    projectId: 'database-for-iot-project',
    authDomain: 'database-for-iot-project.firebaseapp.com',
    databaseURL: 'https://database-for-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'database-for-iot-project.appspot.com',
    measurementId: 'G-01E8EXTVR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeNGRIMUxSinlptGlnnj7xqdHq9ltbB_U',
    appId: '1:1000802414043:android:caaf241017b2a2f8424bfe',
    messagingSenderId: '1000802414043',
    projectId: 'database-for-iot-project',
    databaseURL: 'https://database-for-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'database-for-iot-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFnDTvEZjuzozXacfitcT7nw4p4trHXg0',
    appId: '1:1000802414043:ios:3b5dc2c60b0d3074424bfe',
    messagingSenderId: '1000802414043',
    projectId: 'database-for-iot-project',
    databaseURL: 'https://database-for-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'database-for-iot-project.appspot.com',
    iosBundleId: 'com.example.smartGardenApp',
  );
}
